# Generated by Django 4.0.4 on 2022-06-15 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sem_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('stud_id', models.IntegerField(primary_key=True, serialize=False)),
                ('roll_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_name', models.CharField(max_length=50)),
                ('sub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.department')),
                ('sem_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Term1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('out_of', models.IntegerField()),
                ('sem_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.semester')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.student')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subjects')),
                ('year_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.year')),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='year_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.year'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.year'),
        ),
        migrations.AddField(
            model_name='student',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.department'),
        ),
    ]
