# Generated by Django 4.0.4 on 2022-06-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_department_semester_student_subjects_year_term1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('out_of', models.IntegerField()),
                ('sem_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.semester')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.student')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('out_of', models.IntegerField()),
                ('sem_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.semester')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.student')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subjects')),
            ],
        ),
    ]
