# Generated by Django 4.0.4 on 2022-06-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_term2_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term1',
            name='year_no',
        ),
    ]
