# Generated by Django 4.0.4 on 2022-06-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_term1_year_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_stack_student_activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.student')),
            ],
        ),
    ]
