# Generated by Django 4.0.4 on 2022-06-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_teacher_stack_student_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_stack_student_activities',
            name='stud_id',
            field=models.IntegerField(),
        ),
    ]
