# Generated by Django 4.0.4 on 2022-06-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_teacher_stack_student_activities_stud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_stack_student_activities',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
